---
development:
  cloud_name: antiquarium
  api_key: '371812777248624'
  api_secret: NdcbZ8hwYEvUXAcdWy9AqQlgGW0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: antiquarium
  api_key: '371812777248624'
  api_secret: NdcbZ8hwYEvUXAcdWy9AqQlgGW0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: antiquarium
  api_key: '371812777248624'
  api_secret: NdcbZ8hwYEvUXAcdWy9AqQlgGW0
  enhance_image_tag: true
  static_image_support: false
