---
development:
  cloud_name: zserver
  api_key: '618129751437753'
  api_secret: OyeB3UXWTK_fflpeVu4PaQOqCXE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: zserver
  api_key: '618129751437753'
  api_secret: OyeB3UXWTK_fflpeVu4PaQOqCXE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: zserver
  api_key: '618129751437753'
  api_secret: OyeB3UXWTK_fflpeVu4PaQOqCXE
  enhance_image_tag: true
  static_image_support: false
