# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce6693bd2b00a400ea3af6eb19a90e1bbdfd1b9e5278cb4913f59de5dc580ab18e2cf29185d9297e055f6e7abd9ed5f1b7039cf07ff1ee073b70ad4326b6a8f7

test:
  secret_key_base: 9ccaeb67297e614656cdd67391608288497d9f379f39ba8d3ab94b27011bc56a767a4c0f6c290f6685926c5ce7045b99accc3d4e8ebc223ebeb897ce1425d5ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
