embedly:
  key:        '1ad7edac464f4bd5a1d828bf5a82fcb1'
  user_agent: 'Mozilla/5.0 (compatible; antiquarium/0.1; contact@antiquarium.io)'

aws:
  access_key_id:     'AKIAJQBHPNNCLCEENDWA'
  secret_access_key: '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'
  region:            'us-west-1'
  directory:         'antiquarium'