# Verbs for event interactions
Verb.create(display: "sold to",        keyword: "sold_to",        components: ['date', 'failed', 'details', 'primary_actor', 'secondary_actor', 'price'])
Verb.create(display: "transported to", keyword: "transported_to", components: ['date', 'failed', 'details', 'primary_actor', 'location'])
Verb.create(display: "lent to",        keyword: "lent_to",        components: ['date', 'failed', 'details', 'primary_actor', 'secondary_actor'])
Verb.create(display: "donated to",     keyword: "donated_to",     components: ['date', 'failed', 'details', 'primary_actor', 'secondary_actor', 'price'])
Verb.create(display: "consigned to",   keyword: "consigned_to",   components: ['date', 'failed', 'details', 'primary_actor', 'secondary_actor', 'price'])
Verb.create(display: "returned to",    keyword: "returned_to",    components: ['date', 'failed', 'details', 'primary_actor', 'secondary_actor'])
Verb.create(display: "offered to",     keyword: "offered_to",     components: ['date', 'failed', 'details', 'primary_actor', 'secondary_actor', 'price'])
Verb.create(display: "recommended to", keyword: "recommended_to", components: ['date', 'failed', 'details', 'primary_actor', 'secondary_actor', 'price'])
Verb.create(display: "examined",       keyword: "examined",       components: ['date', 'failed', 'details', 'primary_actor'])
Verb.create(display: "published",      keyword: "published",      components: ['date', 'details', 'primary_actor'])
Verb.create(display: "found at",       keyword: "found",          components: ['date', 'details', 'primary_actor', 'location'])
Verb.create(display: "claimed",        keyword: "claimed",        components: ['date', 'failed', 'details', 'primary_actor'])
Verb.create(display: "transferred to", keyword: "transferred_to", components: ['date', 'failed', 'details', 'primary_actor', 'secondary_actor'])